sudo: required
language: python
python: 3.5
before_script:
  - sudo apt update
  - sudo apt install -y python3-gdal
  - sudo apt install -y python3-pip
  - sudo pip3 install pillow
script:
  - set -e
  - python3 polygon2mbtiles.py example_files/San_Francisco_Shipyard.geojson
  - if [ -f example_files/San_Francisco_Shipyard_digital_globe_standard.mbtiles ];
    then exit 0;
    else exit 1; fi
branches:
  only:
    - master
