# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TileHuria
                                 A QGIS plugin
 Creates MBTiles from tile servers
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2018-06-09
        copyright            : (C) 2018 by Ramani Huria
        email                : ivan.gayton@hotosm.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Ramani Huria'
__date__ = '2018-06-09'
__copyright__ = '(C) 2018 by Ramani Huria'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TileHuria class from file TileHuria.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .tile_huria import TileHuriaPlugin
    return TileHuriaPlugin()
